name: Deploy MERN App

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to use latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Update to use latest version
        with:
          node-version: '16'  # Update to Node.js 16 or later

      - name: Install dependencies
        run: |
          cd frontend  # Assuming your React code is in a directory named "frontend"
          npm install
          cd ../backend  # Assuming your Node.js code is in a directory named "backend"
          npm install

      - name: Build and test
        run: |
          cd frontend
          npm run build
          npm test
          cd ../backend
          npm test

      - name: Start server
        run: |
          cd backend
          npm start
