name: Deploy MERN App

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to use latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Update to use latest version
        with:
          node-version: '16'  # Update to Node.js 20 or later

      - name: Install dependencies
        run: |
          yarn install  

      - name: Build and test
        run: |
          yarn build  
          yarn test  

      - name: Start server
        run: |
          yarn start  # Start the server using yarn
